name: Render and Copy CV

on:
  push:
    branches:
      - main
    paths:
      - "villeneuve_cv/villeneuve_cv2.Rmd"
  workflow_dispatch:

jobs:
  render-and-copy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install R and dependencies
        uses: r-lib/actions/setup-r@v2

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-R-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-R-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages("remotes", repos="https://packagemanager.posit.co/cran/__linux__/latest")'
          Rscript -e 'remotes::install_cran(c("rmarkdown", "tinytex", "vitae", "scholar", "rorcid", "rcrossref", "ggforce", "ggraph", "purrr", "yaml", "tidyr", "dplyr"), dependencies=TRUE)'

      - name: Install Minimal TinyTeX
        run: |
          Rscript -e 'if (!tinytex::is_tinytex()) tinytex::install_tinytex()'
          Rscript -e 'tinytex::tlmgr_install(c("titlesec", "fancyhdr", "enumitem"))'

      - name: Render CV
        run: |
          rmarkdown::render("villeneuve_cv/villeneuve_cv2.Rmd", output_format = "pdf_document")
        shell: Rscript {0}
