name: Render Rmd to PDF

on:
  push:
    paths:
      - '**.Rmd'

jobs:
  render-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.0'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libfontconfig1-dev libssl-dev libxml2-dev

    - name: Install R packages
      run: |
        install.packages(c("scholar", "systemfonts", "textshaping", "ragg", "ggforce", "ggraph", "tidyverse"))

    - name: Render RMarkdown
      run: |
        R -e "rmarkdown::render('villeneuve_cv2.Rmd')"

    - name: Check out the target repository
      uses: actions/checkout@v3
      with:
        repository: villesci/villesci.github.io
        path: main
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy PDF to target repository
      run: |
        cp villeneuve_cv/villenuve_cv2.pdf main/

    - name: Commit and push PDF
      run: |
        cd main
        git config --global user.email "andrewrvilleneuve@gmail.com"
        git config --global user.name "villesci"
        git add .
        git commit -m "Add rendered PDF"
        git push
