name: Render and Copy CV

on:
  push:
    branches:
      - main
    paths:
      - "villeneuve_cv/villeneuve_cv2.Rmd"
  workflow_dispatch:

jobs:
  render-and-copy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "tinytex", "vitae", "scholar", "rorcid", "rcrossref", "purrr", "yaml", "tidyr", "dplyr"),dependencies=T)'
          Rscript -e 'tinytex::install_tinytex()'

      - name: Render CV
        run: |
          rmarkdown::render("villeneuve_cv/villeneuve_cv2.Rmd", output_format = "pdf_document")
        shell: Rscript {0}

      - name: Set up SSH for villesci repo
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VILLESI_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone villesci repo
        run: |
          git clone git@github.com:your-username/villesci.git
          cp villeneuve_cv/villeneuve_cv2.pdf villesci/villeneuve_cv2.pdf

      - name: Commit and Push PDF to villesci
        run: |
          cd villesci
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add villeneuve_cv2.pdf
          git commit -m "Updated CV PDF: $(date)" || echo "No changes to commit"
          git push
